ALTER TABLE `archivedfeed` MODIFY COLUMN `imageurl` VARCHAR(1000) NULL;
ALTER TABLE `feed` MODIFY COLUMN `imageurl` VARCHAR(1000) NULL;

ALTER TABLE `archivedfeed` MODIFY COLUMN `url` VARCHAR(1000) NULL;
ALTER TABLE `feed` MODIFY COLUMN `url` VARCHAR(1000) NULL;
